# Default values for croc-hunter.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value

serviceType: ClusterIP
servicePort: 80
containerPort: 8080
component: "croc-hunter"
replicas: 3
image: "r.cfcr.io/jldeen/jldeen/crochunter"
imageTag: '${{CF_BRANCH_TAG_NORMALIZED}}-${{CF_SHORT_REVISION}}'
imagePullPolicy: "Always"
## If you have a private registry you specify a secret to use
imagePullSecrets: "codefresh-secrets"
cpu: "10m"
memory: "128Mi"
## Ingress settings
ingress:
  enabled: true
  hostname: crochunter.aks.az.jessicadeen.com
  annotations:
     kubernetes.io/ingress.class: nginx
     kubernetes.io/tls-acme: "true"
  tls: true
## PodDisruptionBudget
pdb:
  enabled: false
  minAvailable: 2
